name: Get HM University Certificate
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document - St. Chi
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: stchi-cert.tex

      - name: Compile LaTeX document - St. Linus
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: stlinus-cert.tex

      - name: Create dist and mv
        run: |
          mkdir dist
          mv stchi-cert.pdf dist/stchi-cert.pdf
          mv stlinus-cert.pdf dist/stlinus-cert.pdf

      - name: Convert to png
        uses: JacobLinCool/piconvert@0.4.2
        with:
          src: ./dist
          dist: ./dist
          inputs: pdf
          outputs: svg, png
          force: false
          verbose: false
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "HM University Certificate"
          path: |
            ./dist/